/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "success-emerald": "#10b981",
        "on-surface-variant": "#3f484c",
        "surface-container-low": "#f3f4f6",
        "primary-fixed-dim": "#88d1eb",
        "on-secondary-fixed": "#001e2d",
        "inverse-surface": "#2e3132",
        "tertiary-container": "#679db6",
        "secondary-fixed-dim": "#a0ccea",
        "secondary-container": "#b4e0fe",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d9dadc",
        "on-secondary-container": "#38647e",
        "on-error": "#ffffff",
        "secondary": "#37637d",
        "on-tertiary-fixed": "#001f2a",
        "surface-container": "#edeef0",
        "primary": "#07677e",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#bde9ff",
        "tertiary": "#2b657c",
        "surface": "#f8f9fb",
        "background": "#f8f9fb",
        "ink-black": "#0a0a0a",
        "surface-container-high": "#e7e8ea",
        "tertiary-fixed-dim": "#98cee8",
        "inverse-on-surface": "#f0f1f3",
        "steel-blue": "#719CB8",
        "secondary-fixed": "#c6e7ff",
        "on-tertiary-fixed-variant": "#084d63",
        "error": "#ba1a1a",
        "on-surface": "#191c1e",
        "on-primary-container": "#003340",
        "on-secondary-fixed-variant": "#1c4b64",
        "surface-container-highest": "#e1e2e4",
        "on-error-container": "#93000a",
        "navy-deep": "#024A60",
        "surface-white": "#ffffff",
        "on-primary-fixed": "#001f28",
        "surface-tint": "#07677e",
        "outline-variant": "#bfc8cc",
        "inverse-primary": "#88d1eb",
        "on-tertiary-container": "#003343",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f8f9fb",
        "on-secondary": "#ffffff",
        "on-background": "#191c1e",
        "primary-container": "#559fb8",
        "outline": "#6f787d",
        "on-primary-fixed-variant": "#004e60",
        "surface-variant": "#e1e2e4",
        "primary-fixed": "#b6eaff"
      },
      spacing: {
        "xxl": "48px",
        "max-width": "1280px",
        "xl": "32px",
        "gutter": "24px",
        "sm": "12px",
        "lg": "24px",
        "base": "4px",
        "xs": "8px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "md": "16px"
      },
      fontFamily: {
        "body-md": ["Lexend", "sans-serif"],
        "display": ["Lexend", "sans-serif"],
        "data-tabular": ["Ubuntu", "sans-serif"],
        "title-lg": ["Lexend", "sans-serif"],
        "body-lg": ["Lexend", "sans-serif"],
        "headline-lg-mobile": ["Lexend", "sans-serif"],
        "label-sm": ["Lexend", "sans-serif"],
        "headline-lg": ["Lexend", "sans-serif"],
        "headline-md": ["Lexend", "sans-serif"],
        "label-md": ["Lexend", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display": ["36px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-tabular": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}